# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
 update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"
    clean
    images
    get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "farm_crap_app.xcodeproj")
    build_app(workspace: "farm_crap_app.xcworkspace", scheme: "farm_crap_app")
    upload_to_testflight
  end
  lane :clean do
  clear_derived_data
  end
  lane :images do
   appicon(appicon_image_file: './fastlane/metadata/app_icon.png',
    appicon_devices: [:ipad, :iphone, :ios_marketing],
     appicon_path: 'farm_crap_app/Images.xcassets' )
    add_badge(dark: true)
  end
  lane :deploy do
   produce(
    app_name: 'Farm Crap App Pro'
  )

  deliver(force: true)
  end
end
